### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Sarak-Dahal** [LordRekishi/treasure-hunt-game#1]
I have pulled it but it shows so many error and fixed all of them now after selecting New Game a black screen appears.

**Comment by LordRekishi** [comment]
What errors did you fix? What IDE are you using? And did you try the code before fixing the errors.

I didn't intend for anyone to download this code, it's mostly a storage place for my code while I code along to the tutorial series I mentioned in the readme. 

I can try and help you if you really want to, but you might as well follow along the tutorial yourself and recreate it as you would like it.

**Comment by Sarak-Dahal** [comment]
I am using Eclipse, I am new to Java and even learning from Rysnow YouTube but I followed all his tutorials till video 30 then I had an error which took me forever to solve as I didn't want some part of the code so, and I searched for full code and thought I will change/remove something from finalized code but its not working on my end sir, can you help me set this up in my device it really would be a so much grateful.

**Comment by LordRekishi** [comment]
Yeah, I did some changes in my code too, to add encapsulation primarily. I can help you. You have time now or maybe tomorrow? We could use discord or something similar to have a call if you want.

**Comment by Sarak-Dahal** [comment]
Thank you so much, sir, please help me my discord username is ( Dejavu | OKINA#1182 ) 
Let's meet there I will share my screen sir please send me a friend request over there.

**Comment by Sarak-Dahal** [comment]
![image](https://user-images.githubusercontent.com/70499733/193436459-fb642a5d-be50-409f-af7a-48412ce6a39c.png)

**Comment by Sarak-Dahal** [comment]
Now only D key is working while in movement, how can we fix this like nothing happens when we press other keys but it moves to right when D key is pressed

**Comment by Sarak-Dahal** [comment]
Can you commit the latest code please

**Comment by LordRekishi** [comment]
After helping Sarak install Java properly on his computer the code is now working.
