### ISSUE TITLE
Same issue for me!

### ISSUE THREAD

**Issue by tseamuscorlett** [LordRekishi/treasure-hunt-game#2]
I was super happy to see this repo! I've been watching RyiSnow's videos and was looking for a repo.

But I have the same problem as in the other comment: when I run Main, I get a black screen that says "2D Adventure" on top. Was this issue solved?

I use IntelliJ for IDE.

**Comment by tseamuscorlett** [comment]
ok sometimes the game screen appears. I can hear the sound when I press W/A/S/D keys and the spacebar.
I can press the W/A/S/D keys and I hear the "coin" sound sometimes, but the game screen is static and doesn't update itself.

**Comment by LordRekishi** [comment]
I think he fixed it by updating and installing Java properly. He was a new Java user and hadn't installed the latest version. I sent him this and he said it solved it:

https://www.baeldung.com/java-lang-unsupportedclassversion

Do you get any errors?
